### ISSUE TITLE
Как показывает практика если используешь overflow-x: hidden, но не в слайдере или скроллящемся элементе, то ты наговнокодил где то:)

### ISSUE THREAD

**Issue by RobyDoby** [KuraiDaTenshiDesu/practice#25]
https://disk.yandex.ru/i/_RSpbB6nM4V6_g

**Comment by KDTenshi** [comment]
Добавлял его когда только начинал адаптив делать, а то не всегда понятно было, какая часть страницы выходит за границу, а какая правильно отображается
