### ISSUE TITLE
Тоже совет

### ISSUE THREAD

**Issue by RobyDoby** [KuraiDaTenshiDesu/practice#28]
старайся использовать не % а fr юниты, из-за особенностей работы грида с процентами могут возникнуть непредвиденные проблемы. Но в целом, это максимально не критично, в большинстве случаев можно. https://disk.yandex.ru/i/xgsM65eljtjlwA

**Comment by KDTenshi** [comment]
Там проценты только в паре мест были, если не в одном вообще, а так в основном fr и использую
